

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace webshop
{

using System;
using System.Data.Entity;
using System.Data.Entity.Infrastructure;


public partial class webshopEntities : DbContext
{
    public webshopEntities()
        : base("name=webshopEntities")
    {

    }

    protected override void OnModelCreating(DbModelBuilder modelBuilder)
    {
        throw new UnintentionalCodeFirstException();
    }


    public virtual DbSet<Category> Category { get; set; }

    public virtual DbSet<Customer> Customer { get; set; }

    public virtual DbSet<Manufacturer> Manufacturer { get; set; }

    public virtual DbSet<OrderLine> OrderLine { get; set; }

    public virtual DbSet<OrderTable> OrderTable { get; set; }

    public virtual DbSet<Product> Product { get; set; }

}

}

